# Generated by Django 5.1.6 on 2025-02-26 06:33

from django.db import migrations
from accounts.sql import run_sql_scripts


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [migrations.RunPython(run_sql_scripts),]
